---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: dokploy-fleet-ghcr
  namespace: paris-roubaix
spec:
  encryptedData:
    .dockerconfigjson: AgBOmlHKbYDx8DCOhJH30LZY2fZ8otdNFkHlnM4bWu5KoAnv5bmJn11VUYT8gIdl3fUanqtOP3PF/TRe5SiI4ymXrAGSmVCCFjEuaeuCBpxCLXM/i5eImKH94Yi6do4TcXPStWzsd6RcTxCUErDpOGCRQdwqLehDtfMsKutrtHecE3+dW0rsSstBhu5LqazqsRKbb6XcXrTujhYXEds9mK5wDkRp4sHkRA0S6zl99MHDmjAfAb0J2MBNaMHnrwM2ux6JqDuYGWdVimcvZLheZE0O8prEubZ+RNrW0Nl62ENnDzIeiUxgLmGAMixujZ6lVVqC82q0NPX8keAEEkbOaIiCQ8r9QypNE2uq87QjI2vC4bbqEvYWkSBI48n2h5sJ4svVjyXhZI3o191yovgiJXMpAcmzD01jTgOA0IOPSRIYiCBXCKg9EfWC3DHmWFroE+arrZVTpaU7OzhSU3WPqFRelUBTveVo6PGl05VZR6a5rKE9rtyti+PmiTtmkB3XTjzkmS9eLvYqEQRHAr7GbK1c5CSqDoiUbsAku89GkScNvrOX5ip5/2OXnunH/peGzwN7jXxQB+CJ8+C+ZdOLw6TYuj7jfKdChu1s9Pl40yqRj+ccIzRFyUMsEwudAmM45KXnGgiC7kIy3rmrD72dHON70Pu6qXgqznOn6ce6sM2p32z/b7OTDrTeK6nF92am1wReQQGimDnnGboAhgD7Idcgm8hHC08IswxhozzivCA7G0uZ3X0EYElihU7yiESr3AtZufaPld+dfcaG5KV+HWF0GewMcZwM5BPk1lA3C/Ugdjf4E+obalzVYaKd8fp4XvaLteVlln6tid+zVZBXOxP9+TcDUT1J5ShwBeqbGkD8XtEZxrZJP9AcFtgZIyjDkpLm1oHy1r1LYJveCGMEzooIo6nTu7mxP2inXsNJEPAAgCx7sPBpNy9N
  template:
    metadata:
      name: dokploy-fleet-ghcr
      namespace: paris-roubaix
    type: kubernetes.io/dockerconfigjson
