apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: paris-roubaix
resources:
  - ../../base
labels:
  - pairs:
      app.kubernetes.io/instance: paris-roubaix
images:
  - name: ghcr.io/gateszhangc/paris-roubaix
    newName: registry.144.91.77.245.sslip.io/paris-roubaix
    newTag: a580fabaca3992fada7299e13b4e7a6269b352b0
