apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: paris-roubaix
  namespace: argocd
spec:
  project: paris-roubaix
  source:
    repoURL: https://github.com/gateszhangc/paris-roubaix.git
    targetRevision: main
    path: deploy/k8s/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: paris-roubaix
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
